name: catalyst-ai-agent
region: nyc
services:
- name: api
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/catalyst-ai-agent
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: SUPABASE_SERVICE_ROLE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: MONGODB_URI
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "3000"
  - key: NODE_ENV
    scope: RUN_TIME
    value: "production"
